### ISSUE TITLE
I also can not demo this code helping? I install right python tf and so on

### ISSUE THREAD

**Issue by XINYUCHENmb95408** [scut-mingqinchen/self2self#6]
tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node MaxPool_1}}]]
Traceback (most recent call last):
  File "/root/py3env/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/root/py3env/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/py3env/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node MaxPool_1}}]]

**Comment by xfliu1998** [comment]
I met the same question with you . How did you solve it?

**Comment by XINYUCHENmb95408** [comment]
> 我也遇到了你同樣的問題。您是如何解決的？

I find i use worry cuda  tf1.14.0 must use cuda 10.0  but i am 10.1
